server:
  port: 8080
spring:
  application:
    name: proposta
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${BANCO_URL:jdbc:mysql://localhost:3306/proposta_db?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/users-proposta}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/users-proposta/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: info, healfh, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      - aplicacao=${NOME_DA_APLICACAO:serviço de proposta}
      - ambiente=${AMBIENTE:desenvolvimento}

cartoes:
  url: ${CARTOES_URL:http://localhost:8888/api/cartoes}

solicitacao:
  url: ${SOLICITACAO_URL:http://localhost:9999/api/solicitacao}
